name: thermostat
description: Thermostat widget for Flutter projects.

version: 2.0.0
homepage: https://github.com/kelegorm/thermostat

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
